### ISSUE TITLE
Scheduled messages don't send properly

### ISSUE THREAD

**Issue by czue** [dimagi/mpact#20]
Crash log below

```
celery_1        | [2021-04-09 13:42:04,779: ERROR/MainProcess] Task mpact.tasks.send_msgs[b73b05f8-fccf-4b47-9c83-b5dcdf1b306a] raised unexpected: TypeError("object _AsyncGeneratorContextManager can't be used in 'await' expression")
celery_1        | Traceback (most recent call last):
celery_1        |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 405, in trace_task
celery_1        |     R = retval = fun(*args, **kwargs)
celery_1        |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 697, in __protected_call__
celery_1        |     return self.run(*args, **kwargs)
celery_1        |   File "/code/mpact/tasks.py", line 27, in send_msgs
celery_1        |     return new_or_current_event_loop().run_until_complete(
celery_1        |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
celery_1        |     return future.result()
celery_1        |   File "/code/mpact/tasks.py", line 36, in send_msg
celery_1        |     async with await start_bot_client() as bot:
celery_1        | TypeError: object _AsyncGeneratorContextManager can't be used in 'await' expression
```

**Comment by bderenzi** [comment]
Closing as I think we're all sorted on scheduled messages
