### ISSUE TITLE
500 error on download schedules

### ISSUE THREAD

**Issue by bderenzi** [dimagi/mpact#29]
On a clean install with no chats, it throws an error because there are no sheets added to the excel file when it tries to export.

```
2021-05-04 18:00:52,402 - p26 {/usr/local/lib/python3.8/site-packages/daphne/http_protocol.py:160} - DEBUG - HTTP b'GET' request for ['172.19.0.1', 62540]
Internal Server Error: /api/schedules.xlsx
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
response = get_response(request)
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
return view_func(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
return self.dispatch(request, *args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
response = self.handle_exception(exc)
File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
self.raise_uncaught_exception(exc)
File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
raise exc
File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)
File "/code/mpact/views.py", line 149, in get
response = HttpResponse(databook.export("xlsx"), content_type=xlsx)
File "/usr/local/lib/python3.8/site-packages/tablib/core.py", line 885, in export
return fmt.export_book(self, **kwargs)
File "/usr/local/lib/python3.8/site-packages/tablib/formats/_xlsx.py", line 58, in export_book
wb.save(stream)
File "/usr/local/lib/python3.8/site-packages/openpyxl/workbook/workbook.py", line 407, in save
save_workbook(self, filename)
File "/usr/local/lib/python3.8/site-packages/openpyxl/writer/excel.py", line 293, in save_workbook
writer.save()
File "/usr/local/lib/python3.8/site-packages/openpyxl/writer/excel.py", line 275, in save
self.write_data()
File "/usr/local/lib/python3.8/site-packages/openpyxl/writer/excel.py", line 89, in write_data
archive.writestr(ARC_WORKBOOK, writer.write())
File "/usr/local/lib/python3.8/site-packages/openpyxl/workbook/_writer.py", line 148, in write
self.write_views()
File "/usr/local/lib/python3.8/site-packages/openpyxl/workbook/_writer.py", line 135, in write_views
active = get_active_sheet(self.wb)
File "/usr/local/lib/python3.8/site-packages/openpyxl/workbook/_writer.py", line 33, in get_active_sheet
raise IndexError("At least one sheet must be visible")
IndexError: At least one sheet must be visible
```

**Comment by czue** [comment]
@bderenzi what do you think the "correct" behavior is here? we can't serve a sheet that will work without the telegram id of a chat. I guess we just return one blank sheet with a name like "`Chat Name|<telegram id>`"?

**Comment by bderenzi** [comment]
Right, good question. The order of operations is:

1. create the new group(s) 
2. download the schedule sheet 
3. add in the new messages for the new group(s)
4. upload the sheet
5. for any existing groups where we didn't modify the messages, nothing will change. for the new group(s) we just created and added messages in step 3, they'll be all scheduled

I would guess the server should return some reasonable "not available yet" type error code and the UI should have a little pop up to tell people to create a group before trying to download scheduled messages?

Seems like we want that pop up / toast in some other cases to give UI feedback, so I can start looking into it. Feels like the kind of thing that should be easy with Vue

**Comment by czue** [comment]
Yeah if we can get a notification framework in place that'd be great. At the moment there's also no UI feedback on upload (success or failure). I can change the backend to return a structured thing in this scenario if you can look into that.
